## Perfil PROD (PostgreSQL local o en la nube)
app.env=prod

# Conexión local por ahora (ajusta usuario/clave)
datasource.jdbcUrl=jdbc:postgresql://localhost:5432/cafe
datasource.username=postgres
datasource.password=Esteban-kbza12
datasource.pool.size=10


hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# No mostrar SQL en prod
hibernate.show_sql=true
hibernate.format_sql=true

