## Perfil por defecto
spring.profiles.active=prod

## Configuración común
hibernate.hbm2ddl.auto=none
## Estos flags se definen en cada perfil
# hibernate.show_sql=false
# hibernate.format_sql=true
flyway.enabled=true
flyway.locations=classpath:db/migration
