## Perfil DEV (local) - H2 en archivo
app.env=local

datasource.jdbcUrl=jdbc:h2:file:./data/cafe;AUTO_SERVER=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
datasource.username=sa
datasource.password=
datasource.pool.size=10

hibernate.dialect=org.hibernate.dialect.H2Dialect

# Verbose SQL solo en dev
hibernate.show_sql=true
hibernate.format_sql=true

